baseurl = "https://chmln.github.io/flatpickr/"
languageCode = "en-us"
title = "flatpickr"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    author = "chmln"
    description = "A lightweight and powerful datetimepicker"
    copyright = "Released under the MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/chmln/flatpickr"

    version = ""
    logo = "images/logo.png"
    favicon = "images/logo.png"

    permalink = "#"

    # Custom assets
    custom_css = ["site.css", "bower_components/flatpickr/dist/flatpickr.css"]
    custom_js  = ["bower_components/flatpickr/dist/flatpickr.js", "flatpickr.js"]

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "blue"
        accent  = "light-blue"

    [params.font]
        text = "Libre Franklin"
        code = "Roboto Mono"


[social]
    twitter = ""
    github  = "chmln"
    email   = "hello@email.com"


[[menu.main]]
    name   = "Introduction"
    url    = "/"
    weight = 1

[[menu.main]]
    name   = "Getting Started"
    url    = "getting-started/"
    weight = 2

[[menu.main]]
    name   = "Examples"
    url    = "examples/"
    weight = 3

[[menu.main]]
    name   = "The Flatpickr Instance"
    url    = "instance-methods-properties-elements/"
    weight = 4


[[menu.main]]
    name   = "Events & Hooks"
    url    = "events/"
    weight = 5

[[menu.main]]
    name   = "Localization"
    url    = "localization/"
    weight = 6

[[menu.main]]
    name   = "Config Options"
    url    = "options/"
    weight = 7

[[menu.main]]
    name   = "Formatting Tokens"
    url    = "formatting/"
    weight = 8

[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
